LOCAL_PORT=8080
REDIS_PORT=6379
REDIS_PASSWORD=""
REDIS_HOST="localhost"
DB_NUM=0
SQL_SERVER_PORT=3307
SQL_SERVER_HOST="localhost"
SQL_USERNAME="root"
SQL_PASSWORD="12345678"
DB_NAME="challenge"
BACKUP_INTERVAL_SECONDS=20